#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The ONLY place Brand OS values enter the video engine.

Every other script asks this module. Nothing else re-states a canvas size, a
safe-zone reserve, a watermark geometry or a motion duration. If the canonical
export moves or changes, exactly one file changes.

Source of truth: brand/tokens/adel-v2.1.json, generated by
brand/scripts/build-tokens.mjs from the site token CSS.
"""
import json, os
from pathlib import Path

_CACHE = {}


def _repo_root(start: Path) -> Path:
    p = start.resolve()
    for cand in [p] + list(p.parents):
        if (cand / "brand" / "tokens" / "adel-v2.1.json").exists():
            return cand
    raise FileNotFoundError(
        "Could not locate brand/tokens/adel-v2.1.json. Set ATC_BRAND_TOKENS to its path."
    )


def tokens() -> dict:
    """Load the canonical export once."""
    if "t" in _CACHE:
        return _CACHE["t"]
    override = os.environ.get("ATC_BRAND_TOKENS")
    path = Path(override) if override else _repo_root(Path(__file__)) / "brand" / "tokens" / "adel-v2.1.json"
    if not path.exists():
        raise FileNotFoundError(f"Brand token export not found at {path}")
    _CACHE["t"] = json.loads(path.read_text(encoding="utf-8"))
    _CACHE["path"] = str(path)
    return _CACHE["t"]


def source_path() -> str:
    tokens()
    return _CACHE["path"]


# --- canvas / video profiles -------------------------------------------------

_PROFILE_ALIASES = {
    "9x16": "verticalStandard", "9:16": "verticalStandard", "vertical": "verticalStandard",
    "3x4": "foldPortrait", "3:4": "foldPortrait", "fold-portrait": "foldPortrait",
    "4x3": "foldLandscape", "4:3": "foldLandscape", "fold-landscape": "foldLandscape",
    "16x9": "youtubeLandscape", "16:9": "youtubeLandscape", "youtube": "youtubeLandscape",
}


def profile(name: str = "verticalStandard") -> dict:
    """A canonical VIDEO canvas profile: size, margin, reserves, grid, fps."""
    key = _PROFILE_ALIASES.get(str(name).lower(), name)
    profiles = tokens().get("canvasProfiles", {})
    if key not in profiles:
        available = ", ".join(k for k in profiles if not k.startswith("_"))
        raise KeyError(f"Unknown video profile '{name}'. Available: {available}")
    p = profiles[key]
    return {
        "id": key,
        "width": int(p["width"]),
        "height": int(p["height"]),
        "margin": int(p["margin"]),
        "safe_top": int(p["safeZones"]["top"]),
        "safe_bottom": int(p["safeZones"]["bottom"]),
        "safe_side": int(p["safeZones"].get("left", p["margin"])),
        "fps": int(p.get("fps", 30)),
        "aspect": p.get("aspect"),
        "validation_required": "DERIVED" in str(p.get("provenance", "")).upper(),
        "provenance": p.get("provenance", ""),
    }


def profile_ids() -> list:
    return [k for k in tokens().get("canvasProfiles", {}) if not k.startswith("_")]


# --- watermark ---------------------------------------------------------------

def watermark(short_edge: int) -> dict:
    """Corner watermark geometry for a canvas, from the approved rule.

    The mark scales with the canvas short edge and never falls below the mark
    floor — on a small canvas the floor wins, which is the rule working.
    """
    w = tokens()["watermark"]
    geo = w["geometry"]
    ratio = float(geo["mark-height-ratio"])
    floor = int(tokens()["logo"]["min-size"])
    mark_h = max(floor, round(short_edge * ratio))
    pad = int(geo["padding"])
    mark_w = round(mark_h * float(tokens()["logo"]["ratio"]))
    return {
        "mark_height": mark_h,
        "mark_width": mark_w,
        "padding": pad,
        "plate_width": mark_w + 2 * pad,
        "plate_height": mark_h + 2 * pad,
        "radius": int(geo["radius"]),
        "blur": int(geo["background-blur"]),
        "default_corner": w["placement"]["default"],
        "floor_applied": mark_h == floor and round(short_edge * ratio) < floor,
    }


def watermark_position(prof: dict) -> tuple:
    """Top-left x, y for the watermark, inside the approved safe zone.

    x = margin; y = the top reserve, falling back to the margin where a canvas
    has none. Never outside the safe zone, never centred.
    """
    x = prof["margin"]
    y = prof["safe_top"] if prof["safe_top"] > 0 else prof["margin"]
    return int(x), int(y)


# --- motion ------------------------------------------------------------------

def motion() -> dict:
    m = tokens().get("motion", {})
    return {
        "durations": m.get("duration", {}),
        "easing": m.get("ease", {}),
        "charter": m.get("_charter") or m.get("charter"),
    }


# --- format rules ------------------------------------------------------------

def format_rules(format_id: str) -> dict:
    """Load a production-format JSON (asmr-unboxing, talking-head, ...)."""
    path = Path(__file__).resolve().parents[1] / "formats" / f"{format_id}.json"
    if not path.exists():
        raise FileNotFoundError(f"Unknown production format '{format_id}' ({path})")
    return json.loads(path.read_text(encoding="utf-8"))


def colour(path: str) -> str:
    """A semantic or primitive colour by dotted path, e.g. 'primitives.brand.graphite'."""
    node = tokens()["color"]
    for part in path.split("."):
        node = node[part]
    return node["value"] if isinstance(node, dict) and "value" in node else node


if __name__ == "__main__":
    import sys
    p = profile(sys.argv[1] if len(sys.argv) > 1 else "verticalStandard")
    wm = watermark(min(p["width"], p["height"]))
    print(f"source        {source_path()}")
    print(f"profile       {p['id']}  {p['width']}x{p['height']} @{p['fps']}fps  aspect {p['aspect']}")
    print(f"margin/safe   margin {p['margin']} · top {p['safe_top']} · bottom {p['safe_bottom']} · side {p['safe_side']}")
    print(f"validation    {'DERIVED — device validation required' if p['validation_required'] else 'audited'}")
    print(f"watermark     plate {wm['plate_width']}x{wm['plate_height']} · mark {wm['mark_width']}x{wm['mark_height']}"
          + ("  (floor applied)" if wm["floor_applied"] else ""))
    print(f"placement     {wm['default_corner']} at {watermark_position(p)}")
    print(f"profiles      {', '.join(profile_ids())}")
